/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ProjetoAtividadeJogo;

public class App {
    public static void main(String[] args) {
        Veiculo fusca = new Veiculo(new MotorFusca());
        Veiculo ferrari = new Veiculo(new MotorFerrari());
        Veiculo lamborgini = new Veiculo(new MotorLamborgini());
        
        System.out.println(fusca.acelerar());
        System.out.println(ferrari.acelerar());
        System.out.println(lamborgini.acelerar());
    }
}
